---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: python:3
  commands:
  - python -m pip install --upgrade pip
  - pip install build
  - python -m build
- name: pypi publish
  #when:
  #  event:
  #  - tag
  image: python:3
  environment:
    TWINE_PASSWORD :
      from_secret: pypi_token
  commands:
  - python -m pip install --upgrade pip
  - pip install twine
  - python twine upload --non-interactive -u __token__ --repository-url test.pypi.org/legacy/ dist/*