kind: pipeline
name: default

steps:
- name: build
  image: python:3
  commands:
  - pip -m build
- name: pypi_publish
  image: plugins/pypi
  settings:
    repository: https://test.pypi.org/legacy/
    username: __token__
    password:
      from_secret: pypi_token