---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: python:3
  commands:
  - pip install build
  - python -m build
- name: pypi publish
  #when:
  #  event:
  #  - tag
  image: plugins/pypi
  settings:
    repository: https://test.pypi.org/legacy/
    username: __token__
    password:
      from_secret: pypi_token