---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: python:3
  commands:
  - python -m pip install --upgrade pip
  - pip install build
  - python -m build
- name: pypi publish
  #when:
  #  event:
  #  - tag
  image: python:3
  environment:
    TWINE_NON_INTERACTIVE: true
    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    TWINE_USERNAME: __token__
    TWINE_PASSWORD:
      from_secret: pypi_token
  commands:
  - python -m pip install --upgrade pip
  - pip install twine
  - python -m twine upload dist/*